In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.tokenize import RegexpTokenizer
mytokenizer=RegexpTokenizer('\w+')

In [ ]:
def tok(x):
  return(mytokenizer.tokenize(x))

In [ ]:
import re
def remsc(text):
  pattern='[0-9_]'
  data=[re.sub(pattern,'',i)for i in text]
  return data


In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
sw=stopwords.words('english')
sw

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
s1='Send us your @password'
s2='Send us your #review'
s3='Review your _password'
s4='Review us'
s5='Send your 10 password'
s6='Send us your account'
examples=[s1,s2,s3,s4,s5,s6]

In [ ]:
clean_data=remsc(examples)
clean_data

['Send us your @password',
 'Send us your #review',
 'Review your password',
 'Review us',
 'Send your  password',
 'Send us your account']

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
Vectorizer=TfidfVectorizer(tokenizer=tok,stop_words=sw,ngram_range=(1,2))

In [ ]:
my_final_matrix=Vectorizer.fit_transform(clean_data)
print(my_final_matrix.toarray())

[[0.         0.42428418 0.         0.         0.         0.36357931
  0.         0.42428418 0.36357931 0.         0.61285074 0.        ]
 [0.         0.         0.42428418 0.         0.         0.36357931
  0.         0.42428418 0.36357931 0.         0.         0.61285074]
 [0.         0.49468646 0.49468646 0.71454223 0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.51159697 0.         0.73896835 0.
  0.         0.         0.43839973 0.         0.         0.        ]
 [0.         0.51159697 0.         0.         0.         0.43839973
  0.73896835 0.         0.         0.         0.         0.        ]
 [0.5604894  0.         0.         0.         0.         0.33251546
  0.         0.38803377 0.33251546 0.5604894  0.         0.        ]]


In [ ]:
Vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['account',
 'password',
 'review',
 'review password',
 'review us',
 'send',
 'send password',
 'send us',
 'us',
 'us account',
 'us password',
 'us review']

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
path = '/gdrive/My Drive/Online MLCC : Oct 2021/Data/Classwork/'

In [ ]:
data = pd.read_csv(path+'emails.csv')

In [ ]:
data.head()

text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [ ]:
data.shape

(5728, 2)

In [ ]:
x = data['text']
y = data['spam']

In [ ]:
print("counts of spam: {} , label is {}".format(sum(y==1), '1'))
print("counts of not_spam: {}, label is {}".format(sum(y==0), '0'))

counts of spam: 1368 , label is 1
counts of not_spam: 4360, label is 0


In [ ]:
x =x.values.tolist()
type(x)

list

In [ ]:
data = remsc(x)

In [ ]:
my_Vectorizer = TfidfVectorizer(tokenizer=tok, stop_words=sw, ngram_range=(1, 1))

In [ ]:
Vector_x= my_Vectorizer.fit_transform(data)
print(Vector_x.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
Vector_x.shape

(5728, 33563)

In [ ]:
my_Vectorizer.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['aa',
 'aaa',
 'aaaenerfax',
 'aadedeji',
 'aagrawal',
 'aal',
 'aaldous',
 'aaliyah',
 'aall',
 'aanalysis',
 'aaron',
 'aawesome',
 'ab',
 'aba',
 'abacha',
 'abacus',
 'abahy',
 'abaixo',
 'abandon',
 'abandoned',
 'abandonment',
 'abargain',
 'abarr',
 'abattoir',
 'abb',
 'abbas',
 'abbestellen',
 'abbott',
 'abbreviated',
 'abbreviation',
 'abc',
 'abcsearch',
 'abdalla',
 'abdallat',
 'abdelnour',
 'abdul',
 'abdulla',
 'abdullah',
 'abeis',
 'abel',
 'abello',
 'abels',
 'aber',
 'abernathy',
 'abetted',
 'abeyance',
 'abf',
 'abhay',
 'abide',
 'abidjan',
 'abiiity',
 'abilene',
 'abilities',
 'ability',
 'abilmesi',
 'abit',
 'abitibi',
 'abklaeren',
 'abl',
 'able',
 'abler',
 'abliged',
 'ablx',
 'ably',
 'abn',
 'abnegate',
 'abnormal',
 'abnormality',
 'aboard',
 'abolish',
 'abondantly',
 'abook',
 'aboriginal',
 'abormalities',
 'abort',
 'abortive',
 'abouts',
 'aboutthis',
 'aboutus',
 'aboutvenita',
 'aboveground',
 'abovenet',
 'abovetelefax',
 'abqewvbgf',
 'abr',

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(Vector_x, np.array(y), test_size=0.25)

In [ ]:
y_train.shape, X_train.shape, X_test.shape, y_test.shape

((4296,), (4296, 33563), (1432, 33563), (1432,))

In [ ]:
#for data that has a normal/Gaussian Distribution
from sklearn.naive_bayes import GaussianNB
clf_Gaussian = GaussianNB()
clf_Gaussian.fit(X_train.toarray(), y_train)

y_pred1= clf_Gaussian.predict(X_test.toarray())

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred1))

0.9629888268156425


In [ ]:
#when there is class imbalance
from sklearn.naive_bayes import ComplementNB
clf_complement = ComplementNB()
clf_complement.fit(X_train.toarray(), y_train)

y_pred2= clf_complement.predict(X_test.toarray())

print(accuracy_score(y_test, y_pred2))

0.9574022346368715


In [ ]:
#When there is multivariate input features
from sklearn.naive_bayes import BernoulliNB
clf_Bernoulli = BernoulliNB()
clf_Bernoulli.fit(X_train.toarray(), y_train)

y_pred3= clf_Bernoulli.predict(X_test.toarray())

print(accuracy_score(y_test, y_pred3))

0.9650837988826816


In [ ]:
new_email=[]
new_email.append(input("Enter your email here:"))

In [ ]:
s = remsc(new_email)
Vector_email = my_Vectorizer.transform(s)

In [ ]:
pred =clf_Gaussian.predict(Vector_email.toarray())
pred

In [ ]:
if (pred[0]==0):
  print('The mail is not a spam!')

else:
    print('It is a spam!!')